using System.Security.Claims;
using Erp.Application.Common;
using Erp.Infrastructure.Logging;

namespace Erp.Api.Middleware;

/// <summary>
/// Opens the ambient logging scope required by Constitution Article V.1 so every log emitted
/// during the request carries TenantId, CorrelationId and UserId. Must be registered AFTER
/// <see cref="TenantResolutionMiddleware"/> - the scope reads the already-resolved tenant.
/// </summary>
/// <remarks>
/// Also emits the single Information-level "tenant resolved" log (Constitution V.2: generated by
/// the [LoggerMessage] source generator, never runtime string interpolation). Because it is written
/// inside the scope, that log line carries TenantId in its structured scopes - the acceptance
/// evidence for Task 1.2.
/// </remarks>
public sealed class TenantLoggingScopeMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<TenantLoggingScopeMiddleware> _logger;

    public TenantLoggingScopeMiddleware(RequestDelegate next, ILogger<TenantLoggingScopeMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task InvokeAsync(HttpContext context, ITenantProvider tenantProvider)
    {
        var tenantId = tenantProvider.HasTenant() ? tenantProvider.GetCurrentTenantId().ToString() : "anonymous";
        var correlationId = context.TraceIdentifier;
        var userId = context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "unauthenticated";

        using (_logger.BeginScope(new Dictionary<string, object>
        {
            ["TenantId"] = tenantId,
            ["CorrelationId"] = correlationId,
            ["UserId"] = userId,
            ["RequestPath"] = context.Request.Path.Value ?? "",
        }))
        {
            if (tenantProvider.HasTenant())
            {
                TenantLogs.LogTenantResolved(
                    _logger,
                    tenantProvider.GetCurrentTenantId(),
                    context.Request.Path.Value ?? "");
            }

            await _next(context);
        }
    }
}
