// <auto-generated />
using System;
using AssetHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace AssetHub.Infrastructure.Persistence.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260816201847_AddWorkTaskSoftDeleteAndTaskCommentsConfig")]
    partial class AddWorkTaskSoftDeleteAndTaskCommentsConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetHub.Domain.AssetTemplates.AssetTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedChildTemplateIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BusinessEntityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LifecycleStates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceChecklist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityTypeId");

                    b.HasIndex("Code", "Version", "TenantId")
                        .IsUnique();

                    b.ToTable("AssetTemplates", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CommissionedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ConditionIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Geometry>("Geo")
                        .HasColumnType("geography");

                    b.Property<string>("GeoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetTemplateId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ParentId");

                    b.HasIndex("TenantId", "Path");

                    b.ToTable("Assets", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TenantId", "AssetId");

                    b.ToTable("AssetAttachments", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ValueCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<Geometry>("ValueGeo")
                        .HasColumnType("geography");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ValueText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ValueType");

                    b.HasIndex("TenantId", "AssetId", "AttributeKey");

                    b.ToTable("AssetAttributeValues", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetConditionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConditionIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TenantId", "AssetId");

                    b.ToTable("AssetConditionHistories", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetHierarchy", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("DescendantId", "Depth");

                    b.ToTable("AssetHierarchies", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetLifecycleEvents", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Catalogs.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetModulesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("Catalogs", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Catalogs.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "Code", "TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("CatalogItems", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Catalogs.CatalogItemTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId", "Locale")
                        .IsUnique();

                    b.ToTable("CatalogItemTranslations", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.EntityTypes.BusinessEntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultCatalogIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnabledModules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique();

                    b.ToTable("BusinessEntityTypes", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.IncidentTemplates.IncidentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LifecycleStates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version", "TenantId")
                        .IsUnique();

                    b.ToTable("IncidentTemplates", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Geometry>("Geo")
                        .HasColumnType("geography");

                    b.Property<string>("GeoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IncidentTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PriorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IncidentTemplateId");

                    b.HasIndex("TenantId", "AssetId");

                    b.HasIndex("TenantId", "State");

                    b.ToTable("Incidents", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Incidents.IncidentAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TenantId", "IncidentId");

                    b.ToTable("IncidentAttachments", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Incidents.IncidentLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentLifecycleEvents", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.MaintenanceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PreventivePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("PreventivePlanId");

                    b.HasIndex("TenantId", "AssetId");

                    b.HasIndex("TenantId", "State");

                    b.ToTable("MaintenanceOrders", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.MaintenancePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaintenanceOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("MaintenanceOrderId");

                    b.HasIndex("TenantId", "MaintenanceOrderId");

                    b.ToTable("MaintenanceParts", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.PreventivePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoAssign")
                        .HasColumnType("bit");

                    b.Property<string>("ConditionRuleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DefaultAssignedEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultAssignedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DueDateOffsetDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedEntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetTemplateId");

                    b.HasIndex("TenantId", "NextRunAt");

                    b.ToTable("PreventivePlans", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.PreventivePlanExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GeneratedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GeneratedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Occurrence")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PreventivePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PreventivePlanId");

                    b.HasIndex("TenantId", "AssetId");

                    b.HasIndex("TenantId", "PreventivePlanId", "Occurrence");

                    b.HasIndex("TenantId", "PreventivePlanId", "AssetId", "Occurrence")
                        .IsUnique();

                    b.ToTable("PreventivePlanExecutionLogs", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "UserId", "IsRead");

                    b.ToTable("Notifications", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleCatalogItemId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Employees", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.EmployeeAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "EmployeeId");

                    b.ToTable("EmployeeAvailabilities", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Teams", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TenantId", "EmployeeId");

                    b.HasIndex("TenantId", "TeamId");

                    b.ToTable("TeamMembers", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskId");

                    b.HasIndex("TenantId", "WorkTaskId");

                    b.ToTable("TaskComments", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CapturedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskId");

                    b.HasIndex("TenantId", "WorkTaskId");

                    b.ToTable("TaskEvidences", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskRecurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskTemplateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive", "NextRunAt");

                    b.ToTable("TaskRecurrences", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskId");

                    b.HasIndex("TenantId", "WorkTaskId");

                    b.ToTable("TaskStatusHistories", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndependent")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MaintenanceOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreventivePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriorityCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TaskRecurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskTypeCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("AssignedTeamId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("MaintenanceOrderId");

                    b.HasIndex("PreventivePlanId");

                    b.HasIndex("PriorityCatalogItemId");

                    b.HasIndex("TaskRecurrenceId");

                    b.HasIndex("TaskTypeCatalogItemId");

                    b.HasIndex("TenantId", "AssetId");

                    b.HasIndex("TenantId", "AssignedEmployeeId");

                    b.HasIndex("TenantId", "AssignedTeamId");

                    b.HasIndex("TenantId", "DueAt");

                    b.HasIndex("TenantId", "IncidentId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "MaintenanceOrderId");

                    b.HasIndex("TenantId", "PreventivePlanId");

                    b.HasIndex("TenantId", "TaskRecurrenceId");

                    b.HasIndex("TenantId", "State", "IsDeleted");

                    b.ToTable("WorkTasks", "tenant");
                });

            modelBuilder.Entity("AssetHub.Domain.AssetTemplates.AssetTemplate", b =>
                {
                    b.HasOne("AssetHub.Domain.EntityTypes.BusinessEntityType", "BusinessEntityType")
                        .WithMany()
                        .HasForeignKey("BusinessEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessEntityType");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.Asset", b =>
                {
                    b.HasOne("AssetHub.Domain.AssetTemplates.AssetTemplate", "AssetTemplate")
                        .WithMany()
                        .HasForeignKey("AssetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Assets.Asset", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssetTemplate");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetAttachment", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetAttributeValue", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetConditionHistory", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany("ConditionHistory")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetHierarchy", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Ancestor")
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Assets.Asset", "Descendant")
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.AssetLifecycleEvent", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany("LifecycleEvents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetHub.Domain.Catalogs.CatalogItem", b =>
                {
                    b.HasOne("AssetHub.Domain.Catalogs.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("AssetHub.Domain.Catalogs.CatalogItemTranslation", b =>
                {
                    b.HasOne("AssetHub.Domain.Catalogs.CatalogItem", null)
                        .WithMany("Translations")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetHub.Domain.Incidents.Incident", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.IncidentTemplates.IncidentTemplate", "IncidentTemplate")
                        .WithMany()
                        .HasForeignKey("IncidentTemplateId");

                    b.Navigation("Asset");

                    b.Navigation("IncidentTemplate");
                });

            modelBuilder.Entity("AssetHub.Domain.Incidents.IncidentAttachment", b =>
                {
                    b.HasOne("AssetHub.Domain.Incidents.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AssetHub.Domain.Incidents.IncidentLifecycleEvent", b =>
                {
                    b.HasOne("AssetHub.Domain.Incidents.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.MaintenanceOrder", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Incidents.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId");

                    b.HasOne("AssetHub.Domain.Maintenance.PreventivePlan", "PreventivePlan")
                        .WithMany()
                        .HasForeignKey("PreventivePlanId");

                    b.Navigation("Asset");

                    b.Navigation("Incident");

                    b.Navigation("PreventivePlan");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.MaintenancePart", b =>
                {
                    b.HasOne("AssetHub.Domain.Catalogs.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Maintenance.MaintenanceOrder", "MaintenanceOrder")
                        .WithMany("Parts")
                        .HasForeignKey("MaintenanceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("MaintenanceOrder");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.PreventivePlan", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.AssetTemplates.AssetTemplate", "AssetTemplate")
                        .WithMany()
                        .HasForeignKey("AssetTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("AssetTemplate");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.PreventivePlanExecutionLog", b =>
                {
                    b.HasOne("AssetHub.Domain.Maintenance.PreventivePlan", "PreventivePlan")
                        .WithMany()
                        .HasForeignKey("PreventivePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreventivePlan");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.Employee", b =>
                {
                    b.HasOne("AssetHub.Domain.Catalogs.CatalogItem", "RoleCatalogItem")
                        .WithMany()
                        .HasForeignKey("RoleCatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleCatalogItem");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.EmployeeAvailability", b =>
                {
                    b.HasOne("AssetHub.Domain.Staff.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.TeamMember", b =>
                {
                    b.HasOne("AssetHub.Domain.Staff.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Staff.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskComment", b =>
                {
                    b.HasOne("AssetHub.Domain.Tasks.WorkTask", "WorkTask")
                        .WithMany("TaskComments")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskEvidence", b =>
                {
                    b.HasOne("AssetHub.Domain.Tasks.WorkTask", "WorkTask")
                        .WithMany()
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.TaskStatusHistory", b =>
                {
                    b.HasOne("AssetHub.Domain.Tasks.WorkTask", "WorkTask")
                        .WithMany("StatusHistory")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.WorkTask", b =>
                {
                    b.HasOne("AssetHub.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Staff.Employee", "AssignedEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Staff.Team", "AssignedTeam")
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Incidents.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Maintenance.MaintenanceOrder", "MaintenanceOrder")
                        .WithMany()
                        .HasForeignKey("MaintenanceOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Maintenance.PreventivePlan", "PreventivePlan")
                        .WithMany()
                        .HasForeignKey("PreventivePlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Catalogs.CatalogItem", "PriorityCatalogItem")
                        .WithMany()
                        .HasForeignKey("PriorityCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Tasks.TaskRecurrence", "TaskRecurrence")
                        .WithMany()
                        .HasForeignKey("TaskRecurrenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetHub.Domain.Catalogs.CatalogItem", "TaskTypeCatalogItem")
                        .WithMany()
                        .HasForeignKey("TaskTypeCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("AssignedTeam");

                    b.Navigation("Incident");

                    b.Navigation("MaintenanceOrder");

                    b.Navigation("PreventivePlan");

                    b.Navigation("PriorityCatalogItem");

                    b.Navigation("TaskRecurrence");

                    b.Navigation("TaskTypeCatalogItem");
                });

            modelBuilder.Entity("AssetHub.Domain.Assets.Asset", b =>
                {
                    b.Navigation("ConditionHistory");

                    b.Navigation("LifecycleEvents");
                });

            modelBuilder.Entity("AssetHub.Domain.Catalogs.CatalogItem", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AssetHub.Domain.Maintenance.MaintenanceOrder", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AssetHub.Domain.Staff.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AssetHub.Domain.Tasks.WorkTask", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("TaskComments");
                });
#pragma warning restore 612, 618
        }
    }
}
