using Erp.Domain.Common;

namespace Erp.Domain.Entities.Security;

public class User : ITenantEntity
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Email { get; set; } = string.Empty;
    public string FullName { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>
    /// MFA (module 15-user-profile): TOTP is active only when this flag is set by a successful
    /// <c>VerifyMfaCommand</c>. <c>EnableMfaCommand</c> stages the secret without flipping it.
    /// </summary>
    public bool TwoFactorEnabled { get; set; }

    /// <summary>
    /// Brute-force guard (spec §2/§3.1): incremented on every failed password verification,
    /// reset to zero on success. At <see cref="ProfileRules.MaxFailedAccessAttempts"/> the
    /// account locks until <see cref="LockoutEnd"/>.
    /// </summary>
    public int AccessFailedCount { get; set; }

    /// <summary>UTC instant until which authentication is rejected when the account is locked.</summary>
    public DateTimeOffset? LockoutEnd { get; set; }

    /// <summary>
    /// Staged/active TOTP shared secret (Base32, no padding). Generated by
    /// <c>EnableMfaCommand</c>; never returned by reads except as part of the otpauth URI.
    /// </summary>
    public string? AuthenticatorKey { get; set; }

    public ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
    public ICollection<UserRecoveryCode> RecoveryCodes { get; set; } = new List<UserRecoveryCode>();
}
